# Package Overview
package_name: bike_sharing_model

# Data Files
training_data_file: bike_sharing-dataset.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: cnt

pipeline_name: bike_sharing_model
pipeline_save_file: bike_sharing__model_output_v

features:      # final features to be use
  - season
  - hr
  - holiday 
  - weekday 
  - workingday
  - temp
  - atemp
  - hum
  - windspeed
  - registered
  - cnt
  - yr
  - month


unused_fields:  # Features to drop before pipeline
  - dteday
  - casual
  - registered


# Features inside processing pipeline

embarked_var: Embarked  # first imputatation , then --> Mappeing
  
gender_var: Sex

title_var: Title

age_var: Age 

gender_mappings:
  female: 0
  male: 1

embarked_mappings:
  S: 0
  C: 1
  Q: 2

title_mappings:
  Mrs: 4
  Master: 3
  Miss: 2
  Mr: 1
  Other: 0

  
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 5

